### List all passwords

GET http://localhost:3000/passwords HTTP/1.1

### Get a single password

GET http://localhost:3000/passwords/1 HTTP/1.1

### Create a new password

POST http://localhost:3000/passwords HTTP/1.1
content-type: application/json

{
    "id": 1,
    "password": "123456789"
}

### Delete a passwords to the limit

DELETE http://localhost:3000/passwords/1 HTTP/1.1
content-type: application/json
