### List all products

GET http://localhost:3000/passwords HTTP/1.1

### Get a single product

GET http://localhost:3000/passwords/1 HTTP/1.1

### Create a new product

POST http://localhost:3000/passwords HTTP/1.1
content-type: application/json

{
    "id": 1,
    "password": "123456789"
}

### Delete a product

DELETE http://localhost:3000/passwords/1 HTTP/1.1
content-type: application/json
