### List all products

GET http://localhost:3000/products

### List all products

GET http://localhost:3000/products?page=1&limit=10&search=Apple HTTP/1.1

### Get a single product

GET http://localhost:3000/products/1 HTTP/1.1

### Create a new product

POST http://localhost:3000/products HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjoxLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNzQ3MjMxNzQ3LCJleHAiOjQzMzkyMzE3NDd9.TwGg9zvziaXeVqx_cY5dnE_Mre92AYcQBSNf-Xa5oGk

{
    "name": "AirPods Pro",
    "category": "Electronics",
    "brand": "Apple",
    "tags": [
        "wireless",
        "noise-cancelling",
        "earbuds"
    ],
    "description": "Apple's wireless noise-cancelling earbuds with adaptive transparency and spatial audio.",
    "image": "https://notjustdev-dummy.s3.us-east-2.amazonaws.com/ecom/airpodspro.jpg",
    "price": 249.99
}

### Update an existing product

PUT http://localhost:3000/products/1 HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJtaWhhaUBwaXN0b2wucm8iLCJyb2xlIjoiYWRtaW4iLCJzdWIiOiJhcGkiLCJpYXQiOjE3NDc3MzU3NDksImV4cCI6MTc1MTMzNTc0OX0.xjrPQVOhHkCzasZ0xJr5r0pY0Rj9HGCzg9U36QLlw2w

{
    "name": "AirPods Pro",
    "description": "Apple's wireless noise-cancelling earbuds with adaptive transparency and spatial audio.",
    "image": "https://notjustdev-dummy.s3.us-east-2.amazonaws.com/ecom/airpodspro.jpg",
    "price": 249.99
}

### Delete a product

DELETE http://localhost:3000/products/10 HTTP/1.1
content-type: application/json
