
### List all tags

GET http://localhost:3000/tags HTTP/1.1
content-type: application/json

### Create a new user

POST http://localhost:3000/tags HTTP/1.1
content-type: application/json

{
    "tag": "earbuds"
}
