
runtime: nodejs22
env: standard
service: default
instance_class: F1

# # The following env variables may contain sensitive information that grants
# # anyone access to your database. Do not add this file to your source control.
# env_variables:
#   INSTANCE_CONNECTION_NAME: <MY-PROJECT>:<INSTANCE-REGION>:<INSTANCE-NAME>
#   DB_USER: MY_DB_USER
#   DB_PASS: MY_DB_PASSWORD
#   DB_NAME: MY_DATABASE
